server:
  port: 9092

spring:
  application:
    name: CUSTOMER-CATALOGUE-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/customercataloguedb
    username: customer
    password: Customer123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
